// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"997347a85960618cdca2c70b1e224b72972c0369b49fca5d6a07f74ba83a06fa21eb3a57094b3a925f7a29728646f0984b5638479667620db583d71eb00d13d3"}}
];
